[package]
name = "globe-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A library for geographic coordinates management"
readme = "./README.md"

[dependencies]

[dev-dependencies]
float-cmp = "0.9.0"
