[package]
name = "globe-rs"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "A library for the management of geographic coordinates"
readme = "./README.md"

[dependencies]

[dev-dependencies]
float-cmp = "0.9.0"
